﻿﻿﻿/**
 * Datart
 *
 * Copyright 2021
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChartConfig } from 'app/types/ChartConfig';

const config: ChartConfig = {
  datas: [
    {
      label: 'column',
      key: 'column',
      type: 'group',
      options: {
        sortable: { backendSort: false },
      },
    },
    {
      label: 'row',
      key: 'row',
      type: 'group',
      options: {
        sortable: { backendSort: false },
      },
      drillable: false,
      drillContextMenuVisible: true,
    },
    {
      label: 'metrics',
      key: 'metrics',
      type: 'aggregate',
      actions: {
        NUMERIC: ['aggregate', 'alias', 'format', 'sortable'],
        STRING: ['aggregate', 'alias', 'format', 'sortable'],
      },
      options: {
        sortable: { backendSort: false },
      },
    },
    {
      label: 'filter',
      key: 'filter',
      type: 'filter',
    },
    {
      label: 'info',
      key: 'info',
      type: 'info',
    },
  ],
  styles: [
    {
      label: 'layout.title',
      key: 'layout',
      comType: 'group',
      rows: [
        {
          label: 'layout.hierarchyType',
          key: 'hierarchyType',
          default: 'grid',
          comType: 'select',
          options: {
            translateItemLabel: true,
            items: [
              { label: 'layout.grid', value: 'grid' },
              { label: 'layout.tree', value: 'tree' },
              { label: 'layout.gridTree', value: 'grid-tree' },
            ],
          },
        },
        {
          label: 'layout.metricPlacement',
          key: 'metricPlacement',
          default: 'columns',
          comType: 'select',
          options: {
            translateItemLabel: true,
            items: [
              { label: 'layout.inColumns', value: 'columns' },
              { label: 'layout.inRows', value: 'rows' },
            ],
          },
        },
        {
          label: 'layout.widthType',
          key: 'widthType',
          default: 'compact',
          comType: 'select',
          options: {
            translateItemLabel: true,
            items: [
              { label: 'layout.compact', value: 'compact' },
              { label: 'layout.adaptive', value: 'adaptive' },
              { label: 'layout.columnAdaptive', value: 'colAdaptive' },
            ],
          },
        },
        {
          label: 'layout.cornerText',
          key: 'cornerText',
          default: '',
          comType: 'input',
        },
        {
          label: 'layout.showSeriesNumber',
          key: 'showSeriesNumber',
          default: false,
          comType: 'checkbox',
        },
        {
          label: 'layout.emptyPlaceholder',
          key: 'emptyPlaceholder',
          default: '-',
          comType: 'input',
        },
      ],
    },
    {
      label: 'cell.title',
      key: 'cell',
      comType: 'group',
      rows: [
        {
          label: 'cell.dataWidth',
          key: 'dataWidth',
          default: { width: 120, columnWidths: [] },
          comType: 'pivotColumnWidth',
          options: { min: 40 },
        },
        {
          label: 'cell.dataHeight',
          key: 'dataHeight',
          default: 32,
          comType: 'inputNumber',
          options: { min: 20 },
        },
        {
          label: 'cell.rowWidth',
          key: 'rowWidth',
          default: 120,
          comType: 'inputNumber',
          options: { min: 40 },
        },
        {
          label: 'cell.treeWidth',
          key: 'treeWidth',
          default: 220,
          comType: 'inputNumber',
          options: { min: 80 },
        },
        {
          label: 'cell.columnHeight',
          key: 'columnHeight',
          default: 32,
          comType: 'inputNumber',
          options: { min: 20 },
        },
        {
          label: 'cell.wordWrap',
          key: 'wordWrap',
          default: false,
          comType: 'checkbox',
        },
        {
          label: 'cell.maxLines',
          key: 'maxLines',
          default: 2,
          comType: 'inputNumber',
          options: { min: 1, max: 10 },
        },
        {
          label: 'cell.headerAlign',
          key: 'headerAlign',
          default: 'center',
          comType: 'select',
          options: {
            translateItemLabel: true,
            items: [
              { label: 'cell.left', value: 'left' },
              { label: 'cell.center', value: 'center' },
              { label: 'cell.right', value: 'right' },
            ],
          },
        },
        {
          label: 'cell.dataAlign',
          key: 'dataAlign',
          default: 'right',
          comType: 'select',
          options: {
            translateItemLabel: true,
            items: [
              { label: 'cell.left', value: 'left' },
              { label: 'cell.center', value: 'center' },
              { label: 'cell.right', value: 'right' },
            ],
          },
        },
      ],
    },
    {
      label: 'interaction.title',
      key: 'interaction',
      comType: 'group',
      rows: [
        {
          label: 'interaction.freezeRowHeader',
          key: 'freezeRowHeader',
          default: true,
          comType: 'checkbox',
        },
        {
          label: 'interaction.frozenRows',
          key: 'frozenRows',
          default: 0,
          comType: 'inputNumber',
          options: { min: 0 },
        },
        {
          label: 'interaction.frozenColumns',
          key: 'frozenColumns',
          default: 0,
          comType: 'inputNumber',
          options: { min: 0 },
        },
        {
          label: 'interaction.enableResize',
          key: 'enableResize',
          default: true,
          comType: 'checkbox',
        },
        {
          label: 'interaction.enableCopy',
          key: 'enableCopy',
          default: true,
          comType: 'checkbox',
        },
        {
          label: 'interaction.copyWithHeader',
          key: 'copyWithHeader',
          default: true,
          comType: 'checkbox',
        },
        {
          label: 'interaction.hoverHighlight',
          key: 'hoverHighlight',
          default: true,
          comType: 'checkbox',
        },
        {
          label: 'interaction.selectedHighlight',
          key: 'selectedHighlight',
          default: true,
          comType: 'checkbox',
        },
        {
          label: 'interaction.brushSelection',
          key: 'brushSelection',
          default: true,
          comType: 'checkbox',
        },
      ],
    },
    {
      label: 'totals.title',
      key: 'totals',
      comType: 'group',
      rows: [
        {
          label: 'totals.aggregation',
          key: 'aggregation',
          default: 'SUM',
          comType: 'select',
          options: {
            translateItemLabel: true,
            items: [
              { label: 'totals.sum', value: 'SUM' },
              { label: 'totals.min', value: 'MIN' },
              { label: 'totals.max', value: 'MAX' },
              { label: 'totals.avg', value: 'AVG' },
              { label: 'totals.count', value: 'COUNT' },
            ],
          },
        },
        {
          label: 'cell.rowTotalsSettings',
          key: 'rowTotalsSettings',
          default: [],
          comType: 'pivotColumnSettings',
          options: { mode: 'totals' },
        },
        {
          label: 'totals.rowGrandTotal',
          key: 'rowGrandTotal',
          default: true,
          comType: 'checkbox',
        },
        {
          label: 'totals.rowSubTotal',
          key: 'rowSubTotal',
          default: false,
          comType: 'checkbox',
        },
        {
          label: 'totals.rowTotalAtTop',
          key: 'rowTotalAtTop',
          default: false,
          comType: 'checkbox',
        },
        {
          label: 'totals.columnGrandTotal',
          key: 'columnGrandTotal',
          default: true,
          comType: 'checkbox',
        },
        {
          label: 'totals.columnSubTotal',
          key: 'columnSubTotal',
          default: false,
          comType: 'checkbox',
        },
        {
          label: 'totals.columnTotalAtLeft',
          key: 'columnTotalAtLeft',
          default: false,
          comType: 'checkbox',
        },
      ],
    },
    {
      label: 'condition.title',
      key: 'condition',
      comType: 'group',
      rows: [
        {
          label: 'condition.enableTextColor',
          key: 'enableTextColor',
          default: true,
          comType: 'checkbox',
        },
        {
          label: 'condition.negativeColor',
          key: 'negativeColor',
          default: '#cf1322',
          comType: 'fontColor',
        },
        {
          label: 'condition.positiveColor',
          key: 'positiveColor',
          default: '#237804',
          comType: 'fontColor',
        },
        {
          label: 'condition.enableBackground',
          key: 'enableBackground',
          default: false,
          comType: 'checkbox',
        },
        {
          label: 'condition.threshold',
          key: 'threshold',
          default: 0,
          comType: 'inputNumber',
        },
        {
          label: 'condition.belowColor',
          key: 'belowColor',
          default: '#fff1f0',
          comType: 'fontColor',
        },
        {
          label: 'condition.aboveColor',
          key: 'aboveColor',
          default: '#f6ffed',
          comType: 'fontColor',
        },
        {
          label: 'condition.enableDataBar',
          key: 'enableDataBar',
          default: false,
          comType: 'checkbox',
        },
        {
          label: 'condition.dataBarColor',
          key: 'dataBarColor',
          default: '#5b8ff9',
          comType: 'fontColor',
        },
      ],
    },
    {
      label: 'theme.title',
      key: 'theme',
      comType: 'group',
      rows: [
        {
          label: 'theme.headerBackground',
          key: 'headerBackground',
          default: '#d9eaf7',
          comType: 'fontColor',
        },
        {
          label: 'theme.headerTextColor',
          key: 'headerTextColor',
          default: '#1f4e78',
          comType: 'fontColor',
        },
        {
          label: 'theme.bodyBackground',
          key: 'bodyBackground',
          default: '#ffffff',
          comType: 'fontColor',
        },
        {
          label: 'theme.alternateBackground',
          key: 'alternateBackground',
          default: '#f7fbff',
          comType: 'fontColor',
        },
        {
          label: 'theme.bodyTextColor',
          key: 'bodyTextColor',
          default: '#262626',
          comType: 'fontColor',
        },
        {
          label: 'theme.borderColor',
          key: 'borderColor',
          default: '#b8c8d8',
          comType: 'fontColor',
        },
        {
          label: 'theme.selectedColor',
          key: 'selectedColor',
          default: '#bae7ff',
          comType: 'fontColor',
        },
        {
          label: 'theme.headerFont',
          key: 'headerFont',
          comType: 'font',
          default: {
            fontFamily: 'Microsoft YaHei',
            fontSize: 12,
            fontWeight: 'bold',
            fontStyle: 'normal',
            color: '#1f4e78',
          },
        },
        {
          label: 'theme.bodyFont',
          key: 'bodyFont',
          comType: 'font',
          default: {
            fontFamily: 'Microsoft YaHei',
            fontSize: 12,
            fontWeight: 'normal',
            fontStyle: 'normal',
            color: '#262626',
          },
        },
      ],
    },
  ],
  settings: [
    {
      label: 'viz.palette.setting.paging.title',
      key: 'paging',
      comType: 'group',
      rows: [
        {
          label: 'viz.palette.setting.paging.pageSize',
          key: 'pageSize',
          default: 1000,
          comType: 'inputNumber',
          options: {
            needRefresh: true,
            step: 1,
            min: 0,
          },
        },
      ],
    },
  ],
  interactions: [
    {
      label: 'drillThrough.title',
      key: 'drillThrough',
      comType: 'checkboxModal',
      default: false,
      options: { modalSize: 'middle' },
      rows: [
        {
          label: 'drillThrough.title',
          key: 'setting',
          comType: 'interaction.drillThrough',
        },
      ],
    },
    {
      label: 'viewDetail.title',
      key: 'viewDetail',
      comType: 'checkboxModal',
      default: false,
      options: { modalSize: 'middle' },
      rows: [
        {
          label: 'viewDetail.title',
          key: 'setting',
          comType: 'interaction.viewDetail',
        },
      ],
    },
  ],
  i18ns: [
    {
      lang: 'zh-CN',
      translation: {
        style: {
          title: '表格样式',
          enableExpandRow: '行表头折叠',
          enableHoverHighlight: '启用联动高亮',
          enableSelectedHighlight: '启用选中高亮',
          enableAdjustRowHeight: '启用调整行高',
          enableAdjustColumnWidth: '启用调整列宽',
          metricNameShowIn: {
            label: '指标名称位置',
            inCol: '列表头',
            inRow: '行表头',
          },
          tableSize: '表格大小',
          tableHeaderStyle: '表头样式',
          tableBodyStyle: '表体样式',
          bgColor: '背景颜色',
          font: '字体',
          align: '对齐方式',
          colHeight: '列表头高度',
          rowWidth: '行表头宽度',
          height: '单元格高度',
          width: '单元格宽度',
        },
        layout: {
          title: '表格布局',
          hierarchyType: '行表头布局',
          grid: '平铺',
          tree: '树状',
          gridTree: '树状平铺',
          metricPlacement: '指标名称位置',
          inColumns: '挂列',
          inRows: '挂行',
          widthType: '列宽布局',
          compact: '紧凑',
          adaptive: '整体自适应',
          columnAdaptive: '数据列自适应',
          cornerText: '角头文本',
          showSeriesNumber: '显示序号',
          emptyPlaceholder: '空值占位符',
        },
        cell: {
          title: '单元格',
          dataWidth: '数据列宽',
          columnWidths: '数据列宽',
          rowTotalsSettings: '行汇总',
          dataHeight: '数据行高',
          rowWidth: '行表头列宽',
          treeWidth: '树状行表头宽度',
          columnHeight: '列表头行高',
          wordWrap: '自动换行',
          maxLines: '最大行数',
          headerAlign: '表头对齐',
          dataAlign: '数据对齐',
          left: '左对齐',
          center: '居中',
          right: '右对齐',
        },
        pivot: {
          column: {
            noMetrics: '请先添加指标字段',
            widthPlaceholder: '列宽',
            totals: '汇总',
            configure: '配置',
          },
        },
        interaction: {
          title: '交互与冻结',
          freezeRowHeader: '冻结行表头',
          frozenRows: '冻结顶部数据行数',
          frozenColumns: '冻结左侧数据列数',
          enableResize: '允许拖拽调整宽高',
          enableCopy: '允许复制',
          copyWithHeader: '复制时包含表头',
          hoverHighlight: '悬停高亮',
          selectedHighlight: '选中行列联动高亮',
          brushSelection: '允许刷选',
        },
        totals: {
          title: '小计与总计',
          aggregation: '汇总方式',
          sum: '求和',
          min: '最小值',
          max: '最大值',
          avg: '平均值',
          count: '计数',
          rowGrandTotal: '显示行总计',
          rowSubTotal: '显示行小计',
          rowTotalAtTop: '行汇总置顶',
          columnGrandTotal: '显示列总计',
          columnSubTotal: '显示列小计',
          columnTotalAtLeft: '列汇总置左',
        },
        condition: {
          title: '条件格式',
          enableTextColor: '启用正负值文字颜色',
          negativeColor: '负值颜色',
          positiveColor: '正值颜色',
          enableBackground: '启用阈值背景色',
          threshold: '阈值',
          belowColor: '低于阈值背景色',
          aboveColor: '高于等于阈值背景色',
          enableDataBar: '显示数据条',
          dataBarColor: '数据条颜色',
        },
        theme: {
          title: '主题',
          themeType: '主题类型',
          colHeaderFontColor: '列表头字体颜色',
          evenBgColor: '偶数行背景颜色',
          oddBgColor: '奇数行背景颜色',
          cellBgColorHover: '选中单元格背景颜色',
          colHeaderBgColorHover: '选中列表头背景颜色',
          colHeaderBgColor: '列表头背景颜色',
          prepareSelectMaskBgColor: '画刷层背景颜色',
          linkTextColor: '超链接字体颜色',
          resizeAreaColor: '拖拽区域颜色',
          cellBorderColor: '单元格边框颜色',
          colHeaderBorderColor: '列表头边框颜色',
          verticalSplitLineColor: '垂直分割线颜色',
          horizontalSplitLineColor: '水平分割线颜色',
          cellFontColor: '单元格文字颜色',
          rowHeaderFontColor: '行表头文字颜色',
          type: {
            default: '默认',
            gray: '简约灰',
            colorful: '多彩蓝',
          },
          headerBackground: '表头背景色',
          headerTextColor: '表头文字颜色',
          bodyBackground: '表体背景色',
          alternateBackground: '隔行背景色',
          bodyTextColor: '表体文字颜色',
          borderColor: '边框颜色',
          selectedColor: '选中颜色',
          headerFont: '表头字体',
          bodyFont: '表体字体',
        },
        summary: {
          title: '数据汇总',
          rowSummary: '行总计',
          colSummary: '列总计',
          enableTotal: '启用总计',
          enableSubTotal: '启用小计',
          totalPosition: '总计位置',
          totalPositionTop: '顶部',
          totalPositionBottom: '底部',
          subTotalPosition: '小计位置',
          subTotalPositionTop: '顶部',
          subTotalPositionBottom: '底部',
          aggregateFields: '汇总列',
          summaryAggregation: '总计聚合',
          calcSubAggregation: '小计聚合',
          aggregation: '聚合方式',
          aggregations: {
            sum: '求和',
            min: '最小值',
            max: '最大值',
            avg: '平均值',
          },
          totalPositionType: {
            top: '顶部',
            bottom: '底部',
            left: '左侧',
            right: '右侧',
          },
          subTotal: '小计',
          total: '总计',
          number: '数值',
        },
      },
    },
    {
      lang: 'en-US',
      translation: {
        style: {
          title: 'Table Style',
          enableExpandRow: 'Fold Row',
          enableHoverHighlight: 'Enable Hover Highlight',
          enableSelectedHighlight: 'Enable Selected Highlight',
          enableAdjustRowHeight: 'Enable Adjust Row Height',
          enableAdjustColumnWidth: 'Enable Adjust Column Width',
          metricNameShowIn: {
            label: 'Metric Name Position',
            inCol: 'Col Header',
            inRow: 'Row Header',
          },
          tableSize: 'Table Size',
          tableHeaderStyle: 'Table Header Style',
          tableBodyStyle: 'Table Body Style',
          bgColor: 'Background Color',
          font: 'Font',
          align: 'Align',
          colHeight: 'Col Header Height',
          rowWidth: 'Row Header Width',
          height: 'Height',
          width: 'Width',
        },
        layout: {
          title: 'Table Layout',
          hierarchyType: 'Row Header Layout',
          grid: 'Grid',
          tree: 'Tree',
          gridTree: 'Grid Tree',
          metricPlacement: 'Measure Placement',
          inColumns: 'In Columns',
          inRows: 'In Rows',
          widthType: 'Width Layout',
          compact: 'Compact',
          adaptive: 'Adaptive',
          columnAdaptive: 'Column Adaptive',
          cornerText: 'Corner Text',
          showSeriesNumber: 'Show Row Number',
          emptyPlaceholder: 'Empty Placeholder',
        },
        cell: {
          title: 'Cells',
          dataWidth: 'Default Column Width',
          columnWidths: 'Data Column Width',
          rowTotalsSettings: 'Row Totals',
          dataHeight: 'Data Row Height',
          rowWidth: 'Row Header Width',
          treeWidth: 'Tree Header Width',
          columnHeight: 'Column Header Height',
          wordWrap: 'Wrap Text',
          maxLines: 'Maximum Lines',
          headerAlign: 'Header Alignment',
          dataAlign: 'Data Alignment',
          left: 'Left',
          center: 'Center',
          right: 'Right',
        },
        pivot: {
          column: {
            noMetrics: 'Please add metric fields first',
            widthPlaceholder: 'Width',
            totals: 'Total',
            configure: 'Configure',
          },
        },
        interaction: {
          title: 'Interaction and Freeze',
          freezeRowHeader: 'Freeze Row Header',
          frozenRows: 'Frozen Data Rows',
          frozenColumns: 'Frozen Data Columns',
          enableResize: 'Enable Resize',
          enableCopy: 'Enable Copy',
          copyWithHeader: 'Copy with Headers',
          hoverHighlight: 'Hover Highlight',
          selectedHighlight: 'Selected Header Highlight',
          brushSelection: 'Enable Brush Selection',
        },
        totals: {
          title: 'Subtotals and Grand Totals',
          aggregation: 'Aggregation',
          sum: 'Sum',
          min: 'Minimum',
          max: 'Maximum',
          avg: 'Average',
          count: 'Count',
          rowGrandTotal: 'Show Row Grand Total',
          rowSubTotal: 'Show Row Subtotals',
          rowTotalAtTop: 'Place Row Totals First',
          columnGrandTotal: 'Show Column Grand Total',
          columnSubTotal: 'Show Column Subtotals',
          columnTotalAtLeft: 'Place Column Totals First',
        },
        condition: {
          title: 'Conditional Formatting',
          enableTextColor: 'Color Positive and Negative Values',
          negativeColor: 'Negative Color',
          positiveColor: 'Positive Color',
          enableBackground: 'Enable Threshold Background',
          threshold: 'Threshold',
          belowColor: 'Below Threshold Color',
          aboveColor: 'At or Above Threshold Color',
          enableDataBar: 'Show Data Bars',
          dataBarColor: 'Data Bar Color',
        },
        theme: {
          title: 'Theme',
          themeType: 'Theme Type',
          colHeaderFontColor: 'Col Header Font Color',
          evenBgColor: 'Even Row Background Color',
          oddBgColor: 'Odd Row Background Color',
          cellBgColorHover: 'Selected Cell Background Color',
          colHeaderBgColorHover: 'Selected Col Header Background Color',
          colHeaderBgColor: 'Col Header Background Color',
          prepareSelectMaskBgColor: 'Prepare Select Mask Color',
          linkTextColor: 'Link Text Color',
          resizeAreaColor: 'Resize Area Color',
          cellBorderColor: 'Cell Border Color',
          colHeaderBorderColor: 'Col Header Border Color',
          verticalSplitLineColor: 'Vertical Split Line Color',
          horizontalSplitLineColor: 'Horizontal Split Line Color',
          cellFontColor: 'Cell Font Color',
          rowHeaderFontColor: 'Row Header Font Color',
          type: {
            default: 'Default',
            gray: 'Gray',
            colorful: 'Colorful',
          },
          headerBackground: 'Header Background',
          headerTextColor: 'Header Text Color',
          bodyBackground: 'Body Background',
          alternateBackground: 'Alternate Row Background',
          bodyTextColor: 'Body Text Color',
          borderColor: 'Border Color',
          selectedColor: 'Selection Color',
          headerFont: 'Header Font',
          bodyFont: 'Body Font',
        },
        summary: {
          title: 'Summary',
          rowSummary: 'Row Total',
          colSummary: 'Column Total',
          enableTotal: 'Enable Total',
          totalPosition: 'Total Position',
          totalPositionTop: 'Top',
          totalPositionBottom: 'Bottom',
          enableSubTotal: 'Enable Sub Total',
          subTotalPosition: 'Sub Total Position',
          subTotalPositionTop: 'Top',
          subTotalPositionBottom: 'Bottom',
          aggregateFields: 'Summary Fields',
          summaryAggregation: 'Summary Aggregation',
          calcSubAggregation: 'Calc Sub Aggregation',
          aggregation: 'Aggregation Type',
          aggregations: {
            sum: 'Sum',
            min: 'Min',
            max: 'Max',
            avg: 'Avg',
          },
          totalPositionType: {
            top: 'Top',
            bottom: 'Bottom',
            left: 'Left',
            right: 'Right',
          },
          subTotal: 'Sub Total',
          total: 'Total',
          number: 'Metric',
        },
      },
    },
  ],
};

export default config;
